title: cyfanc
description: "record some code snippets"
author:
  name: "cyfanc"
  email: "test@test.com"
  url: "https://cyfanc.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "cyfanc"
year : "2022"
